FROM node:latest

RUN mkdir -p /home/node/vendorservice/node_modules && chown -R node:node /home/node/vendorservice

WORKDIR /home/node/vendorservice

COPY package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 3006

CMD [ "npm", "start" ]
