FROM node:latest

RUN mkdir -p /home/node/adminservice/node_modules && chown -R node:node /home/node/adminservice

WORKDIR /home/node/adminservice

COPY package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 3001

CMD [ "npm", "start" ]
