FROM node:latest

RUN mkdir -p /home/node/itemservice/node_modules && chown -R node:node /home/node/itemservice

WORKDIR /home/node/itemservice

COPY package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 3002

CMD [ "npm", "start" ]
