FROM node:latest

RUN mkdir -p /home/node/userservice/node_modules && chown -R node:node /home/node/userservice

WORKDIR /home/node/userservice

COPY package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 3004

CMD [ "npm", "start" ]
